package sqlite3

/*
#cgo CFLAGS: -DNDEGUB
#cgo CFLAGS: -DSQLITE_OMIT_TRACE
#cgo CFLAGS: -DSQLITE_OMIT_DEPRECATED
#cgo CFLAGS: -DSQLITE_OMIT_LOAD_EXTENSION
#cgo CFLAGS: -DSQLITE_OMIT_UTF16
#cgo CFLAGS: -DSQLITE_OMIT_EXPLAIN
#cgo CFLAGS: -DSQLITE_OMIT_PROGRESS_CALLBACK

#cgo CFLAGS: -DSQLITE_USE_URI
#cgo CFLAGS: -DSQLITE_THREADSAFE=0
#cgo CFLAGS: -DSQLITE_DEFAULT_MEMSTATUS=0
#cgo CFLAGS: -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
*/
import "C"
