gcc sqlite3_example.c ../sqlite3.c \
-O3 \
-Wall \
-pg \
-I ../ \
-DNDEGUB \
-DSQLITE_OMIT_TRACE \
-DSQLITE_OMIT_DEPRECATED \
-DSQLITE_OMIT_LOAD_EXTENSION \
-DSQLITE_OMIT_UTF16 \
-DSQLITE_OMIT_EXPLAIN \
-DSQLITE_OMIT_PROGRESS_CALLBACK \
-DSQLITE_USE_URI \
-DSQLITE_THREADSAFE=0 \
-DSQLITE_DEFAULT_MEMSTATUS=0 \
-DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 \
-DSQLITE_ENABLE_FTS5 \
-lm

#valgrind --leak-check=full -v ./a.out
